### ISSUE TITLE
Create render dashboard: set up deployable database

### ISSUE THREAD

**Issue by brianaqp** [Team-Llama-Llama/llama-llama-back-end#16]

**Comment by prestonb91** [comment]
Internal DB_URL: postgresql://llama:Zx9DIDMuVmZlDla9BDZDhXE8Q036k0z7@dpg-csbmos9u0jms73ff3l80-a/lms_db_rj7i

**Comment by brianaqp** [comment]
excelente! hope tomorrow we can deploy
