### ISSUE TITLE
Create standard endpoints for server

### ISSUE THREAD

**Issue by brianaqp** [Team-Llama-Llama/llama-llama-back-end#9]

**Comment by brianaqp** [comment]
Only for Path and Modules

**Comment by prestonb91** [comment]
@brianaqp @miwhipps 
I added the endpoints and also set up a controller model format in the src file. 
You can see it below and would like to talk about this tomorrow together to agree on the endpoints and how we set up the backend before making the pull request. 
https://github.com/Team-Llama-Llama/llama-llama-back-end/tree/d352280a6a1fa7b3e5250d6b475d7fa32818b9a1/server/src

**Comment by brianaqp** [comment]
awesome! remember that is more easier to read the changes if you added to the PR

**Comment by brianaqp** [comment]
Changes

1. Instead of calling our directories as our db entities, its better to use the names of the arquitecture we are using, for example: "models", "controllers".
2. Every model should be a class and it will encapsulete knex.
3. We will keep the user routes commented until we add Auth.
4. We are gonna define some proper names for the controller function calls.

**Comment by brianaqp** [comment]
And for yea, amazing idea!
